version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Update Django patches
  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "django"
        update-types: ["version-update:semver-minor"]
    allow:
      - dependency-name: "django"
