version: 2
updates:
  # Update Django patches
  - package-ecosystem: "pip"
    directory: "/requirements/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "django"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
    allow:
      - dependency-name: "django"
