# Generated by Django 3.1.13 on 2021-11-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0067_campaign_historicalcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='hide_from_overview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcasetype',
            name='hide_from_overview',
            field=models.BooleanField(default=False),
        ),
    ]
