# Generated by Django 3.2.11 on 2022-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casehandling', '0069_sentusernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentusernotification',
            name='notification_type',
            field=models.CharField(default='not specified', max_length=255),
            preserve_default=False,
        ),
    ]
