# Generated by Django 3.2.11 on 2022-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='order',
            field=models.FloatField(blank=True, help_text='If not null, show this casetype on the front page. In order of this value.', null=True),
        ),
    ]
